### ISSUE TITLE
What's port you use in .env file? beginning I use port 3000, it works and created webhook successful, but after add Bot, I rerun application, maybe have conflict port 3000

### ISSUE THREAD

**Issue by thanhbinh0995** [cosmicjs/facebook-bot#2]

**Comment by aspiringguru** [comment]
the tutorial nominated use of localtunnel to port forward from port 5000 to port 3000.
package.json nominates port 3000 in this line below.

"forward": "lt --port 3000 --subdomain noahsmessengerbot",

**Comment by aspiringguru** [comment]
see also my separate issue just raised.  

my guess is thanbinh0995 has a duplicate process running already using port 3000

**Comment by thanhbinh0995** [comment]
I think I use another process with 3000 port
